
package com.unimet.interfaz;
import com.unimet.clases.PCB;
import com.unimet.estructuras.Cola;


/**
 *
 * @author chris
 */
public class Simulacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Simulacion.class.getName());
// Tus colas
    Cola<PCB> colaListos = new Cola<>();
    Cola<PCB> colaBloqueados = new Cola<>();
    
    PCB procesoEnCpu = null;
    boolean corriendo = false;
    int quantum = 5; // Cada proceso tiene solo 5 turnos seguidos
    int contadorQuantum = 0; // Para contar cuánto lleva el proceso actual
    int relojGlobal = 0;
    public Simulacion() {
        initComponents();
        spnQuantum.setValue(5);      // Quantum de 5 turnos
        spnVelocidad.setValue(1000); // 1 segundo de velocidad (para empezar lento)
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtColaListos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtColaBloqueados = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spnQuantum = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spnVelocidad = new javax.swing.JSpinner();
        lblReloj = new javax.swing.JLabel();
        cmbAlgoritmos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COLA DE LISTOS");

        txtColaListos.setColumns(20);
        txtColaListos.setRows(5);
        jScrollPane1.setViewportView(txtColaListos);

        jLabel2.setText("COLA DE BLOQUEADOS");

        txtColaBloqueados.setColumns(20);
        txtColaBloqueados.setRows(5);
        jScrollPane2.setViewportView(txtColaBloqueados);

        jLabel3.setText("CPU - PROCESANDO");

        lblId.setText("ID: ---");

        lblEstado.setText("Estado: ---");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado)
                    .addComponent(lblId)
                    .addComponent(jLabel3))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnCrear.setText("Crear Proceso");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnIniciar.setText("Iniciar Simulación");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        jLabel4.setText("Quantum:");

        jLabel5.setText("Velocidad (ms):");

        lblReloj.setText("Reloj: 0");

        cmbAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "RR", "Prioridad", "SRT", "EDF" }));
        cmbAlgoritmos.addActionListener(this::cmbAlgoritmosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrear)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(spnQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnIniciar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // 1. Crear datos aleatorios para el proceso (Simulando carga de trabajo)
    int instrucciones = (int) (Math.random() * 100) + 10;
    int prioridad = (int) (Math.random() * 3) + 1; // Prioridad 1, 2 o 3
    int deadline = (int) (Math.random() * 200) + 50; 
    
    // 2. Crear el objeto PCB (Tu proceso)
    // El nombre será algo como "Proceso-1", "Proceso-2", etc.
    String nombre = "Proceso-" + (int)(Math.random() * 1000);
    PCB nuevoProceso = new PCB(nombre, prioridad, instrucciones, deadline);
    
    agregarAColaListos(nuevoProceso);
    
    System.out.println("Proceso creado exitosamente: " + nombre);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
    // Evitar que le den click dos veces
    if (corriendo) return;
        corriendo = true;
        
        
        // HILO DEL PLANIFICADOR
        Thread hiloSimulacion = new Thread(() -> {
            while (corriendo) {
                try {
                    
                    // LEER EL QUANTUM EN VIVO DESDE LA VENTANA
                    int quantumActual = (Integer) spnQuantum.getValue();
                    if (quantumActual < 1) quantumActual = 1; // Mínimo 1 para no romper
                    // A. MANEJO DE BLOQUEADOS (I/O)
                    if (!colaBloqueados.isEmpty()) {
                        PCB bloqueado = colaBloqueados.desencolar();
                        bloqueado.setLongitudBloqueo(bloqueado.getLongitudBloqueo() - 1);
                        
                        if (bloqueado.getLongitudBloqueo() <= 0) {
                            bloqueado.setEstado("Listo");
                            bloqueado.setCicloParaBloqueo(-1); 
                            agregarAColaListos(bloqueado);
                            System.out.println(">>> Desbloqueado: " + bloqueado.getNombre());
                        } else {
                            colaBloqueados.encolar(bloqueado);
                        }
                    }

                    // B. PLANIFICADOR CPU (Round Robin)
                    if (procesoEnCpu == null) {
                        if (!colaListos.isEmpty()) {
                            procesoEnCpu = colaListos.desencolar();
                            procesoEnCpu.setEstado("Ejecucion");
                            contadorQuantum = 0;
                            
                            lblId.setText("ID: " + procesoEnCpu.getId());
                            lblEstado.setText("Ejecutando (RR)");
                            refrescarColaListos(); 
                        }
                    } 
                    else {
                        // 1. CHEQUEO DE E/S
                        if (procesoEnCpu.getInstruccionesEjecutadas() == procesoEnCpu.getCicloParaBloqueo()) {
                             System.out.println("!!! Bloqueado por E/S: " + procesoEnCpu.getNombre());
                             procesoEnCpu.setEstado("Bloqueado");
                             colaBloqueados.encolar(procesoEnCpu);
                             procesoEnCpu = null;
                             contadorQuantum = 0;
                             lblId.setText("ID: --- (Bloqueado)");
                             refrescarColaListos();
                        }
                        else {
                            // 2. EJECUTAR
                            procesoEnCpu.avanzarInstruccion();
                            contadorQuantum++;
                            
                            lblEstado.setText("Ejecutando: " + 
                                    procesoEnCpu.getInstruccionesEjecutadas() + " / " + 
                                    procesoEnCpu.getInstruccionesTotales());

                            // 3. CHEQUEO TERMINADO
                            if (procesoEnCpu.getInstruccionesEjecutadas() >= procesoEnCpu.getInstruccionesTotales()) {
                                System.out.println("Terminó: " + procesoEnCpu.getNombre());
                                procesoEnCpu.setEstado("Terminado");
                                procesoEnCpu = null;
                                contadorQuantum = 0;
                                lblId.setText("ID: ---");
                                refrescarColaListos();
                            }
                            // 4. CHEQUEO QUANTUM
                            else if (contadorQuantum >= quantumActual) {
                                System.out.println("Cambio de Contexto (Quantum): Sale " + procesoEnCpu.getNombre());
                                procesoEnCpu.setEstado("Listo");
                                agregarAColaListos(procesoEnCpu);
                                procesoEnCpu = null;
                                contadorQuantum = 0;
                                lblId.setText("ID: --- (Timeout)");
                                refrescarColaListos();
                            }
                        }
                    }
                    
                    // Actualizar GUI Bloqueados
                    if(colaBloqueados.isEmpty()) txtColaBloqueados.setText("");
                    else txtColaBloqueados.setText(colaBloqueados.toString());

                    int velocidad = (Integer) spnVelocidad.getValue();
                    // Protección para que no sea negativo ni cero
                    if (velocidad < 0) velocidad = 0; 
                    relojGlobal++;
                    lblReloj.setText("Reloj Global: " + relojGlobal); // Actualizar etiqueta visual
                    Thread.sleep(velocidad);
                    
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        hiloSimulacion.start();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void cmbAlgoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoritmosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAlgoritmosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Simulacion().setVisible(true));
    }
    
    // Este método actualiza el cuadro de texto con los procesos que quedan
    private void refrescarColaListos() {
        // 1. Borramos lo que hay escrito en la caja de texto
        txtColaListos.setText(""); 
        
        // 2. Pedimos a la cola que nos de su contenido actualizado
        if (!colaListos.isEmpty()) {
            txtColaListos.setText(colaListos.toString());
        }
        
        // 3. Hacemos lo mismo para la cola de bloqueados (por si acaso)
        txtColaBloqueados.setText("");
        if (!colaBloqueados.isEmpty()) {
            txtColaBloqueados.setText(colaBloqueados.toString());
        }
    }
    
    public void agregarAColaListos(PCB proceso) {
        // 1. Preguntamos qué algoritmo está seleccionado en la cajita
        String algoritmo = (String) cmbAlgoritmos.getSelectedItem();
        
        // 2. Dependiendo del algoritmo, insertamos de forma distinta
        switch (algoritmo) {
            case "FCFS":
            case "RR":
                // Para estos, es por orden de llegada (al final)
                colaListos.encolar(proceso); 
                break;
                
            case "Prioridad":
                // Insertamos ordenado por Prioridad (asumiendo que 0 es el código para prioridad en tu Cola)
                colaListos.insertarOrdenado(proceso, 0);
                break;
                
            case "SRT":
                // Insertamos ordenado por Tiempo Restante (código 1)
                colaListos.insertarOrdenado(proceso, 1);
                break;
                
            case "EDF":
                // Insertamos ordenado por Deadline (código 2)
                colaListos.insertarOrdenado(proceso, 2);
                break;
        }
        
        // 3. Actualizamos la visualización en la caja de texto
        refrescarColaListos();
    }
    
    // --- FIN DE LO QUE TIENES QUE PEGAR ---
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox<String> cmbAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JSpinner spnQuantum;
    private javax.swing.JSpinner spnVelocidad;
    private javax.swing.JTextArea txtColaBloqueados;
    private javax.swing.JTextArea txtColaListos;
    // End of variables declaration//GEN-END:variables
}
